-- Supabase Setup SQL for STAC
-- Run this in Supabase Dashboard > SQL Editor

-- Table for storing screens
create table if not exists stac_screens (
  id bigint generated by default as identity primary key,
  name text not null unique,
  json jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table for storing configurations
create table if not exists stac_config (
  id bigint generated by default as identity primary key,
  name text not null unique,
  json jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table for version history
create table if not exists screen_versions (
  id bigint generated by default as identity primary key,
  screen text not null,
  version int not null,
  json jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table stac_screens enable row level security;
alter table stac_config enable row level security;
alter table screen_versions enable row level security;

-- Drop existing policies if they exist
drop policy if exists "Allow all operations on screens" on stac_screens;
drop policy if exists "Allow all operations on configs" on stac_config;
drop policy if exists "Allow all operations on versions" on screen_versions;

-- Create policies to allow all operations
create policy "Allow all operations on screens" on stac_screens for all using (true);
create policy "Allow all operations on configs" on stac_config for all using (true);
create policy "Allow all operations on versions" on screen_versions for all using (true);
