import 'api_method_enum.dart';
import 'api_version_enum.dart';

enum ApiProviderEnum {
  config(
    title: 'App Config',
    path: 'config/apps/',
    method: ApiMethod.get,
    requireToken: false,
    requireDecryption: false,
  ),
  configMenu(
    title: 'App Config Menu',
    path: 'config/menu',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  authorizedApiToken(
    title: 'Get Authorized Api Token dibalite',
    path: 'dibalite/kyc',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  registerCustomer(
    title: 'Register Customer dibalite',
    path: 'dibalite/customer/registration',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  customerInfo(
    title: 'Get Customer Info dibalite',
    path: 'dibalite/customer/info',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getDiscountEffect(
    title: 'Get transaction discount amount',
    path: 'customer_club/discount/effect',
    method: ApiMethod.get,
  ),
  getCustomerClubWebViewLink(
    title: 'Customer club web view link',
    path: 'customer_club/link',
    method: ApiMethod.get,
  ),
  cardBalance(
    title: 'Get card balance',
    path: 'pichak/tsm/pin-verification',
    method: ApiMethod.post,
  ),
  uploadCustomerPublicKey(
    title: 'Upload Customer Public Key Dibalite',
    path: 'dibalite/customer/update-public-key',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  getDibalitePublicKey(
    title: 'Get Dibalite Public Key Request',
    path: 'dibalite/inquire/customer/public-key',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getJobsList(
    title: 'Get Jobs List Dibalite',
    path: 'dibalite/occupations',
    method: ApiMethod.get,
  ),
  getDynamicPassword(
    title: 'Get Dynamic Password Pichak',
    path: 'pichak/otp/balance',
    method: ApiMethod.post,
  ),
  submitUserCard(
    title: 'Submit User Card Request',
    path: 'cards/add',
    method: ApiMethod.post,
  ),
  updateUserCard(
    title: 'Update User Card Request',
    path: 'cards/',
    method: ApiMethod.put,
  ),
  deleteUserCard(
    title: 'Delete User Card Request',
    path: 'cards/',
    method: ApiMethod.delete,
  ),
  getListBankData(
    title: 'Get List Bank Data',
    path: 'banks/cards',
    method: ApiMethod.get,
  ),
  getCardOwner(
    title: 'Get Card Owner Request',
    path: 'banks/cards',
    method: ApiMethod.post,
  ),
  cardToCard(
    title: 'Card To Card Request',
    path: 'banks/card_to_card',
    method: ApiMethod.post,
  ),
  cardToCardGardeshgary(
    title: 'Card To Card Gardeshgary Request',
    path: 'banks/gardeshgary/card_to_card',
    method: ApiMethod.post,
  ),
  getCardDynamicPassword(
    title: 'Card dynamic password',
    path: 'banks/otp',
    method: ApiMethod.post,
  ),
  getCards(
    title: 'Get user merged cards from digital banking, notebook and submited cards',
    path: 'dibalite/digital/banking/all/customer/cards',
    method: ApiMethod.get,
  ),
  cardIssuance(
    title: 'Digital banking card issuance',
    path: 'dibalite/cards/issuance',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  changeCardPin(
    title: 'Digital banking change card pin',
    path: 'dibalite/cards/change-pin',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  getCardIssuanceTemplates(
    title: 'Digital banking get card issuance templates',
    path: 'dibalite/cards/templates',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  blockCard(
    title: 'Digital banking block card',
    path: 'dibalite/cards/block',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  changeCardPinArbitrary(
    title: 'Digital banking change card pin arbitrary',
    path: 'dibalite/cards/change-pin-arbitrary',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  cbsSendThirdPersonOTP(
    title: 'CBS send OTP to third person for confirmation',
    path: 'openbanking/third-person/send-otp',
    method: ApiMethod.post,
  ),
  cbsCreditInquiry(
    title: 'CBS credit inquiry',
    path: 'transactions/openbanking/credit-inquiry/fee',
    apiVersion: ApiVersion.v2,
    method: ApiMethod.post,
  ),
  cbsCreditInquiryOrderId(
    title: 'CBS credit inquiry with OrderId',
    path: 'openbanking/inquiry/credit-inquiry-pdf',
    apiVersion: ApiVersion.v2,
    method: ApiMethod.post,
  ),
  cbsFetchDocument(
    title: 'CBS fetch document',
    path: 'openbanking/credit-inquiry/document-fetch/',
    apiVersion: ApiVersion.v2,
    method: ApiMethod.get,
  ),
  getCharities(
    title: 'Get available charities',
    path: 'charities',
    method: ApiMethod.get,
  ),
  donateCharities(
    title: 'Donate to charities',
    path: 'charities/donate/',
    method: ApiMethod.post,
  ),
  getConfigByTitle(
    title: 'Get Config by title',
    path: 'config/by-title/',
    method: ApiMethod.get,
  ),
  matchContacts(
    title: 'Match user contacts',
    path: 'users/mobiles/match',
    method: ApiMethod.post,
  ),
  getCustomerReferrers(
    title: 'Get customer referrers',
    path: 'dibalite/customer-referrers',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  daranLogin(
    title: 'Daran login request',
    path: 'daran/register/login',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2
  ),
  deleteAccountOTPRequest(
    title: 'Delete account OTP request',
    path: 'users/account/delete/otp',
    method: ApiMethod.get,
  ),
  deleteAccount(
    title: 'Delete account',
    path: 'users/account/delete',
    method: ApiMethod.post,
  ),
  saveDepositInNotebook(
    title: 'Save deposit in notebook',
    path: 'cards/deposit',
    method: ApiMethod.post,
  ),
  getDepositNotebook(
    title: 'Get deposit notebook',
    path: 'cards/deposit',
    method: ApiMethod.get,
  ),
  updateDepositNotebook(
    title: 'Update deposit notebook',
    path: 'cards/deposit',
    method: ApiMethod.put,
  ),
  deleteDepositNotebook(
    title: 'Delete deposit notebook',
    path: 'cards/deposit-delete',
    method: ApiMethod.post,
  ),
  getcustomerDeposits(
    title: 'Get Customer Deposits',
    path: 'dibalite/customer/deposits',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  openDeposit(
    title: 'Open Deposit',
    path: 'dibalite/open/deposit',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  getDepositTypes(
    title: 'Get Deposit Types Request',
    path: 'dibalite/customer/deposits/types',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getDepositBalance(
    title: 'Get Deposit Balance Request',
    path: 'dibalite/deposit/balance',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getDepositStatement(
    title: 'Get Deposit Statement Request',
    path: 'dibalite/deposit/statement',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  getDepositStatementWithoutSign(
    title: 'Get Deposit Statement Without Sign Request',
    path: 'dibalite/deposit/statement',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  openLongTermDeposit(
    title: 'Open Long Term Deposit Request',
    path: 'dibalite/open/long-deposit',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  uploadDocumentRequest(
    title: 'Upload Document Request',
    path: 'dibalite/upload/document',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getDigitalDocument(
    title: 'Digital Document Request',
    path: 'dibalite/get/digital/document/',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getPhysicalGiftCardsAmount(
    title: 'Get Physical Gift Cards Amount Request',
    path: 'giftcards/categories',
    method: ApiMethod.get,
  ),
  getGiftCardCosts(
    title: 'Get Physical Costs Request',
    path: 'giftcards/costs',
    method: ApiMethod.get,
  ),
  getGiftCardsList(
    title: 'Get List Physical Gift Card Request',
    path: 'giftcards',
    method: ApiMethod.get,
  ),
  getGiftCardEvents(
    title: 'Get List Event Plan Request',
    path: 'giftcards/events',
    method: ApiMethod.get,
  ),
  getGiftCardDeliveryDates(
    title: 'Get List Delivery Date Data',
    path: 'giftcards/dates/',
    method: ApiMethod.get,
  ),
  payPhysicalGiftCard(
    title: 'Pay Physical Gift Card',
    path: 'giftcards',
    method: ApiMethod.post,
    receiveTimeout: Duration(minutes: 5),
  ),
  getInternetPlansStaticData(
    title: 'Get Internet Static Data',
    path: 'mobiles/data/types',
    method: ApiMethod.get,
  ),
  payInternetPlan(
    title: 'Pay Internet Plan Wallet Request',
    path: 'mobiles/internet/charge',
    method: ApiMethod.post,
  ),
  getBillDetail(
    title: 'Get Bill Detail Data Request',
    path: 'users/bills',
    method: ApiMethod.post,
  ),
  payBill(
    title: 'Pay Bill Internet Request',
    path: 'bills/pay',
    method: ApiMethod.post,
  ),
  getBillDetailWithPayIdBillId(
    title: 'Get Bill Detail With Pay Id Bill Id',
    path: 'bills/info',
    method: ApiMethod.post,
  ),
  getUserBills(
    title: 'Get Bill List Request',
    path: 'users/bills',
    method: ApiMethod.get,
  ),
  getGiftCardMessageList(
    title: 'Get List Message Gift Card Request',
    path: 'giftcards/message/',
    method: ApiMethod.get,
  ),
  getInternetPlans(
    title: 'Get Internet Plans Request',
    path: 'mobiles/internet/plans',
    method: ApiMethod.get,
  ),
  updateBillRequest(
    title: 'Update Bill Request',
    path: 'users/bills/',
    method: ApiMethod.put,
  ),
  deleteBillRequest(
    title: 'Delete Bill Request',
    path: 'users/bills/',
    method: ApiMethod.delete,
    apiVersion: ApiVersion.v2,
  ),
  inquiryBillRequest(
    title: 'Inquiry Bill Request',
    path: 'bills/energies',
    method: ApiMethod.get,
  ),
  changeModernBankingPassword(
    title: 'Modern Banking Password Change',
    path: 'dibalite/modern-banking-password-change',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  getNotifications(
    title: 'Get Notification Request',
    path: 'fcm/messages',
    method: ApiMethod.get,
  ),
  setNotificationRead(
    title: 'Notification Read Request',
    path: 'fcm/message/',
    method: ApiMethod.put,
  ),
  deleteNotification(
    title: 'Delete Notification Request',
    path: 'fcm/message/',
    method: ApiMethod.delete,
  ),
  getPageDataWithoutToken(
    title: 'Get Page Data Request',
    path: 'page/',
    method: ApiMethod.get,
    requireToken: false,
  ),
  getPageData(
    title: 'Get Page Data Request',
    path: 'page/',
    method: ApiMethod.get,
  ),
  getVerificationCode(
    title: 'Get Verification Code Request',
    path: 'users/password/otp',
    method: ApiMethod.post,
    successStatusCodes: [200, 420],
    requireToken: false,
  ),
  verifyCode(
    title: 'Verify Code Request',
    path: 'users/login-shahkar',
    method: ApiMethod.post,
    requireToken: false,
  ),
  getUserProfile(
    title: 'Get User Profile',
    path: 'user',
    method: ApiMethod.get,
  ),
  updateUserProfile(
    title: 'Update User Profile',
    path: 'user',
    method: ApiMethod.put,
  ),
  submitUserFirebaseToken(
    title: 'Submit user Firebase token',
    path: 'fcm/devices',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  logOutUser(
    title: 'Log out user',
    path: 'users/logout',
    method: ApiMethod.get,
  ),
  getUserAvatars(
    title: 'Get Users avatar list',
    path: 'users/avatar',
    method: ApiMethod.get,
  ),
  checkUserIdentityInfo(
    title: 'Check user Shahkar and Identity info',
    path: 'users/check-user-shahkar-info',
    method: ApiMethod.post,
  ),
  fetchUnsignedDocument(
    title: 'Get Unsigned promissory request',
    path: 'promissory/requests/fetch/document',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  getMyPromissories(
    title: 'Get user finalized promissories',
    path: 'promissory/my/promissory',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  getOpenPromissoryRequests(
    title: 'Get user open promissory requests',
    path: 'promissory/requests/open',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  payPromissoryPublishRequest(
    title: 'Pay promissory publish request',
    path: 'transactions/promissory/publish/fee',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  finalizePromissoryPublishRequest(
    title: 'Promissory publish finalize',
    path: 'promissory/publish/finalize',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
    requireBase64EncodedBody: true,
  ),
  getPromissoryPublishPrice(
    title: 'Promissory publish price',
    path: 'promissory/price',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  createPromissoryPublishRequest(
    title: 'Promissory publish request',
    path: 'promissory/publish/request',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  deletePromissoryOpenRequest(
    title: 'Promissory publish request',
    path: 'promissory/requests/delete',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  createPromissoryGuaranteeRequest(
    title: 'Promissory guarantee request',
    path: 'promissory/guarantee/request',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  inquiryPromissory(
    title: 'Promissory inquiry promissoryId',
    path: 'promissory/inquiry',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  finalizePromissoryGuaranteeRequest(
    title: 'Promissory guarantee finalize',
    path: 'promissory/guarantee/finalize',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
    requireBase64EncodedBody: true,
  ),
  inquiryOtherUserName(
    title: 'Other user info inquiry',
    path: 'dibalite/dest/user/info',
    method: ApiMethod.post,
  ),
  createPromissoryEndorsementRequest(
    title: 'Promissory endorsment request',
    path: 'promissory/endorsement/request',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  finalizePromissoryEndorsementRequest(
    title: 'Promissory endorsment finalize',
    path: 'promissory/endorsement/finalize',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
    requireBase64EncodedBody: true,
  ),
  fetchPromissoryDocument(
    title: 'Promissory fetch document',
    path: 'promissory/fetch/document',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  createPromissorySettlementRequest(
    title: 'Promissory settlement request',
    path: 'promissory/settlement/request',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  finalizePromissorySettlementRequest(
    title: 'Promissory settlement finalize',
    path: 'promissory/settlement/finalize',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
    requireBase64EncodedBody: true,
  ),
  createPromissorySettlementGradualRequest(
    title: 'Promissory settlement gradual request',
    path: 'promissory/settlement/gradual/request',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  finalizePromissorySettlementGradualRequest(
    title: 'Promissory settlement gradual finalize',
    path: 'promissory/settlement/gradual/finalize',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
    requireBase64EncodedBody: true,
  ),
  getPromissoryAssets(
    title: 'Get promissory asset',
    path: 'promissory/sign/asset',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  inquiryCompany(
    title: 'Inquiry company',
    path: 'promissory/company/inquiry',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  checkUserSana(
    title: 'Check user has Sana code',
    path: 'openbanking/check-sana',
    method: ApiMethod.get,
  ),
  getOpenPromissoryPublishRequest(
    title: 'Get open promissory publish request',
    path: 'promissory/publish/request/open',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  getMyFullDetailedPromissory(
    title: 'Get all user\'s promissory published and open request',
    path: 'promissory/my/full/detailed/promissory',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  getUserSafeBoxes(
    title: 'Get user safe boxes',
    path: 'safety/deposit/fund/user',
    method: ApiMethod.get,
  ),
  getSafeBoxBranches(
    title: 'Get safe box branches',
    path: 'safety/deposit/branch/list',
    method: ApiMethod.get,
  ),
  getSafeBoxReferDate(
    title: 'Get safe box refer date',
    path: 'safety/deposit/refer/date',
    method: ApiMethod.get,
  ),
  paySafeBoxCost(
    title: 'Pay safe box cost',
    path: 'transactions/deposit/fund/payment',
    method: ApiMethod.post,
  ),
  getSafeBoxVisitDates(
    title: 'Get safe box visit dates',
    path: 'safety/deposit/user/visit',
    method: ApiMethod.get,
  ),
  submitSafeBoxVisitRequest(
    title: 'Submit safe box visit request',
    path: 'safety/deposit/fund/visit',
    method: ApiMethod.post,
  ),
  getSafeBoxVisitDateTime(
    title: 'Get safe box visit dates',
    path: 'safety/deposit/visit/date',
    method: ApiMethod.get,
  ),
  getSafeBoxCities(
    title: 'Get safe box cities',
    path: 'safety/deposit/city/list',
    method: ApiMethod.get,
  ),
  getSimCardChargePlans(
    title: 'Get sim card charge plans',
    path: 'mobiles/charge/plans',
    method: ApiMethod.get,
  ),
  paySimCardChargePlan(
    title: 'Pay sim card charge plan',
    path: 'mobiles/charge',
    method: ApiMethod.post,
  ),
  inquiryIban(
    title: 'Inquiry iban request',
    path: 'dibalite/financial/iban-inquiry',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  transferDepositRequest(
    title: 'Transfer money from user deposit',
    path: 'dibalite/financial/transfer',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  getTransferHistory(
    title: 'Get transfer history',
    path: 'dibalite/financial/transfer-history',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  inquiryTransferStatus(
    title: 'Get transfer status',
    path: 'dibalite/financial/transfer-status-inquiry',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  inquiryAddress(
    title: 'Inquiry address',
    path: 'dibalite/customer/address-inquiry',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  updateAddress(
    title: 'Update address in core banking',
    path: 'dibalite/customer/change-address',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
  ),
  getUserWalletDetail(
    title: 'Get user wallet detail',
    path: 'wallets/balance',
    method: ApiMethod.get,
  ),
  chargeWalletRequest(
    title: 'Charge wallet request',
    path: 'wallets/charge/payment',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  getWalletBalance(
    title: 'Get wallet balance',
    path: 'wallets',
    method: ApiMethod.get,
  ),
  transferWalletRequest(
    title: 'Transfer wallet to wallet',
    path: 'wallets/wallet_to_wallet',
    method: ApiMethod.post,
  ),
  getCustomerInfoWalletRequest(
    title: 'Get customer info wallet request',
    path: 'dibalite/customer/data',
    method: ApiMethod.post,
    successStatusCodes: [200, 420],
    requireBase64EncodedBody: true,
  ),
  getUserProcessInstances(
    title: 'Get user process instances BPMS',
    path: 'dibalite/process/user/processes-instances',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getProcessDetail(
    title: 'Get process detail BPMS',
    path: 'dibalite/process/detail',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getApplicantTaskList(
    title: 'Get applicant task list BPMS',
    path: 'dibalite/task/user-task-list',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getProcessStartFormData(
    title: 'Get process start form data BPMS',
    path: 'dibalite/process/get-start-form-data',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getTaskData(
    title: 'Get task data BPMS',
    path: 'dibalite/task/get-data',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getTaskContractDocument(
    title: 'Get task contract document BPMS',
    path: 'dibalite/documents/',
    method: ApiMethod.post,
  ),
  uploadTaskContractDocument(
    title: 'Upload task contract document BPMS',
    path: 'dibalite/documents/validator/',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getAverageMinimumDepositAmountForLoan(
    title: 'Get average minimum deposit amount for loan BPMS',
    path: 'dibalite/average/minimum/deposit/amount/for/loan',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  smartCheckPersonInfo(
    title: 'Smart check person info',
    path: 'dibalite/ekyc/smart-check-person-info',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  startProcess(
    title: 'Start BPMS process',
    path: 'dibalite/process/start',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
    successStatusCodes: [200, 409],
  ),
  completeTask(
    title: 'Complete BPMS task',
    path: 'dibalite/task/complete',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
    successStatusCodes: [200, 409],
  ),
  inquiryEkycStatus(
    title: 'Inquiry ekyc status',
    path: 'dibalite/ekyc/status/inquiry',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getEkycOTP(
    title: 'Get ekyc OTP',
    path: 'dibalite/ekyc/otp',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
  ),
  validateEkycOTP(
    title: 'Validate ekyc OTP',
    path: 'dibalite/ekyc/person/info',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
  ),
  uploadNationalCardFrontImage(
    title: 'Upload national card front image',
    path: 'dibalite/ekyc/verify/national_id/front/image',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
  ),
  uploadNationalCardRearImage(
    title: 'Upload national card rear image',
    path: 'dibalite/ekyc/verify/national_id/back/image',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
  ),
  verifyPersonImage(
    title: 'Verify person image',
    path: 'dibalite/ekyc/verify/person/image',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
  ),
  uploadBirthCertificateMainPage(
    title: 'Upload birth certificate main page',
    path: 'dibalite/ekyc/verify/birth_certificate/main/image',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
  ),
  uploadBirthCertificateCommentsPage(
    title: 'Upload birth certificate comments page',
    path: 'dibalite/ekyc/verify/birth_certificate/comments/image',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
  ),
  submitSignatureImage(
    title: 'Submit signature image',
    path: 'dibalite/ekyc/register/signature/image',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
  ),
  getEkycAddressInquiry(
    title: 'Get ekyc address inquiry',
    path: 'dibalite/ekyc/address/info',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
  ),
  issueCertificate(
    title: 'Issue certificate',
    path: 'dibalite/ekyc/person/digital/signature/certificate',
    method: ApiMethod.post,
    successStatusCodes: [200, 421],
    requireBase64EncodedBody: true,
    receiveTimeout: Duration(minutes: 3),
  ),
  renewCertificate(
    title: 'Renew certificate',
    path: 'dibalite/renew/certificate',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
    requireEkycSign: true,
    receiveTimeout: Duration(minutes: 3),
  ),
  getActiveCertificate(
    title: 'Get active certificate',
    path: 'dibalite/ekyc/active/certificate',
    method: ApiMethod.post,
    requireBase64EncodedBody: true,
  ),
  getUserTransactions(
    title: 'Get user transactions',
    path: 'users/transactions/',
    method: ApiMethod.get,
  ),
  getUserTransactionByRefId(
    title: 'Get user transaction by ref id',
    path: 'users/transactions/client/ref/',
    method: ApiMethod.get,
  ),
  getAzkiLoanCurrentStep(
    title: 'Get Azki loan current step',
    path: 'dibalite/azki/loan/user/step',
    method: ApiMethod.get,
  ),
  getAzkiLoanDetail(
    title: 'Get Azki loan detail',
    path: 'dibalite/azki/loan/promissory',
    method: ApiMethod.get,
  ),
  submitAzkiLoanCollateralPromissoryData(
    title: 'Submit Azki loan collateral promissory data',
    path: 'dibalite/azki/loan/promissory/submit',
    method: ApiMethod.post,
  ),
  getAzkiLoanContract(
    title: 'Get Azki loan contract',
    path: 'dibalite/generate/azki-loan/document',
    method: ApiMethod.get,
  ),
  submitAzkiLoanSignedContract(
    title: 'Submit Azki loan signed contract',
    path: 'dibalite/signed/azki-loan/document/',
    method: ApiMethod.put,
    requireBase64EncodedBody: true,
  ),
  chequeCreditInquiry(
    title: 'Pichak credit inquiry',
    path: 'pichak/credit-inquiry',
    method: ApiMethod.post,
  ),
  chequeStaticInfoInquiry(
    title: 'Pichak static info inquiry',
    path: 'pichak/static-info-inquiry',
    method: ApiMethod.post,
  ),
  chequeReceiverInquiry(
    title: 'Pichak receiver inquiry',
    path: 'pichak/receiver-inquiry',
    method: ApiMethod.post,
  ),
  chequeRegistration(
    title: 'Pichak cheque registration',
    path: 'pichak/registration',
    method: ApiMethod.post,
  ),
  chequeDynamicInfoInquiry(
    title: 'Pichak dynamic info inquiry',
    path: 'pichak/dynamic-info-inquiry',
    method: ApiMethod.post,
  ),
  chequeConfirmation(
    title: 'Pichak confirmation',
    path: 'pichak/confirmation',
    method: ApiMethod.post,
  ),
  chequeTransfer(
    title: 'Pichak transfer',
    path: 'pichak/transfer',
    method: ApiMethod.post,
  ),
  chequeTransferStatusInquiry(
    title: 'Pichak transfer status inquiry',
    path: 'pichak/transfer-status-inquiry',
    method: ApiMethod.post,
  ),
  chequeTrackingInquiry(
    title: 'Pichak tracking inquiry',
    path: 'pichak/tracking-inquiry',
    method: ApiMethod.post,
  ),
  getChequeRegisterReasonTypes(
    title: 'Pichak get registration reason types',
    path: 'pichak/reason-types',
    method: ApiMethod.get,
  ),
  enrollCardTSM(
    title: 'TSM card enrollment',
    path: 'pichak/tsm/card-enrollment',
    method: ApiMethod.post,
  ),
  reactiveAppTSM(
    title: 'TSM app reactivation',
    path: 'pichak/tsm/app-reactivation',
    method: ApiMethod.post,
  ),
  getCardInfoTSM(
    title: 'TSM get card info',
    path: 'pichak/tsm/get-card-info',
    method: ApiMethod.post,
  ),
  renewCardTSM(
    title: 'TSM get card info',
    path: 'pichak/tsm/renew-cardid',
    method: ApiMethod.post,
  ),
  inquiryCard(
    title: 'Shaparak hub card inquiry',
    path: 'pichak/tsm/transfer/card-inquiry',
    method: ApiMethod.post,
  ),
  cardTransferShaparakHub(
    title: 'Shaparak hub card to card transfer',
    path: 'pichak/tsm/transfer',
    method: ApiMethod.post,
  ),
  inquiryCardTransferShaparakHub(
    title: 'Shaparak hub card to card inquiry',
    path: 'pichak/tsm/transfer/inquiry',
    method: ApiMethod.post,
  ),
  microLendingGetCurrentStep(
    title: 'Get current step micro lending',
    path: 'loan/micro-lending/step',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  microLendingCheckAccess(
    title: 'Check access for micro lending loan',
    path: 'loan/micro-lending/access',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  microLendingGetDeposits(
    title: 'Get deposits for micro lending loan',
    path: 'loan/micro-lending/deposit/list',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  microLendingCheckDeposit(
    title: 'Check deposit for micro lending loan',
    path: 'loan/micro-lending/check/deposit',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  microLendingCheckSana(
    title: 'Check deposit for micro lending loan',
    path: 'loan/micro-lending/check/sana',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  microLendingPayFee(
    title: 'Check deposit for micro lending loan',
    path: 'transactions/loan/micro-lending/fee/payment',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  microLendingSubmitPriceAndDuration(
    title: 'Submit price and duration micro lending loan',
    path: 'loan/micro-lending/price/submit',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  microLendingSubmitSignedContract(
    title: 'Submit signed contract micro lending loan',
    path: 'loan/micro-lending/contract/submit',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
    requireBase64EncodedBody: true,
  ),
  microLendingGetLoanDetail(
    title: 'Check deposit for micro lending loan',
    path: 'loan/micro-lending/detail',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  microLendingCheckSamatCbs(
    title: 'Check parsa lending samat cbs',
    path: 'loan/micro-lending/check/samat-cbs',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  microLendingInquiryCbs(
    title: 'Inquiry parsa lending cbs',
    path: 'loan/micro-lending/inquiry/cbs',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  increaseDepositBalance(
    title: 'Increase deposit balance with ipg',
    path: 'transactions/increase/deposit/balance',
    method: ApiMethod.post,
  ),
  creditCardFacilityAccess(
    title: 'Check user for has requirements for credit card facility',
    path: 'dibalite/credit-card-facility/access',
    method: ApiMethod.get,
  ),
  creditCardFacilityCheckDeposit(
    title: 'Check selected deposit for get list of loan facility',
    path: 'dibalite/credit-card-facility/check/deposit',
    method: ApiMethod.post,
  ),
  creditCardFacilitySubmitPrice(
    title: 'Submit selected price of loan facility',
    path: 'dibalite/credit-card-facility/submit/price',
    method: ApiMethod.post,
  ),
  creditCardFacilityDepositList(
    title: 'Get list of deposit for credit card facility from server',
    path: 'dibalite/credit-card-facility/list/deposit',
    method: ApiMethod.get,
  ),
  parsaLendingOccupationList(
    title: 'Get list of occupation for parsa lending',
    path: 'loan/parsa-lending/occupation',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingChooseOccupation(
    title: 'Choose occupation for parsa lending',
    path: 'loan/parsa-lending/occupation',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingBranchList(
    title: 'Get list of branch for parsa lending',
    path: 'loan/parsa-lending/branch',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingChooseBranch(
    title: 'Choose branch for parsa lending',
    path: 'loan/parsa-lending/branch',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingResidencyList(
    title: 'Get residency list for parsa lending',
    path: 'users/parsa-lending/residency',
    method: ApiMethod.get,
  ),
  parsaLendingChooseResidency(
    title: 'Choose residency for parsa lending',
    path: 'users/parsa-lending/residency',
    method: ApiMethod.post,
  ),
  parsaLendingCheckAccess(
    title: 'Check access for parsa lending',
    path: 'loan/parsa-lending/access',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingDepositList(
    title: 'Get deposit list for parsa lending',
    path: 'loan/parsa-lending/deposit/list',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingCheckDeposit(
    title: 'Check selected deposit for parsa lending',
    path: 'loan/parsa-lending/check/deposit',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingCheckSana(
    title: 'Check sana for parsa lending',
    path: 'loan/parsa-lending/check/sana',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingGetCurrentStep(
    title: 'Get current step parsa lending',
    path: 'loan/parsa-lending/step',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingGetLoanDetail(
    title: 'Get Loan Detail for parsa lending loan',
    path: 'loan/parsa-lending/detail',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingGetPromissory(
    title: 'Get promissory of parsa lending',
    path: 'loan/parsa-lending/promissory',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingSubmitPromissory(
    title: 'Submit promissory of parsa lending',
    path: 'loan/parsa-lending/promissory-submit',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingSubmitPlan(
    title: 'Submit plan of parsa lending',
    path: 'loan/parsa-lending/plan/submit',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingSubmitPrice(
    title: 'Submit price of parsa lending',
    path: 'loan/parsa-lending/price/submit',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingSubmitContract(
    title: 'Submit contract of parsa lending',
    path: 'loan/parsa-lending/contract/submit',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
    requireBase64EncodedBody: true,
  ),
  parsaLendingProcessState(
    title: 'Return process state of parsa lending',
    path: 'loan/parsa-lending/bpms/process-state',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingStartProcess(
    title: 'Start process of parsa lending',
    path: 'loan/parsa-lending/bpms/start-process',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingCompleteTask(
    title: 'Complete task of parsa lending',
    path: 'loan/parsa-lending/bpms/task-complete',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingUploadDocument(
    title: 'Complete task of parsa lending',
    path: 'loan/parsa-lending/document/upload',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingCheckSamatCbs(
    title: 'Check parsa lending samat cbs',
    path: 'loan/parsa-lending/check/samat-cbs',
    method: ApiMethod.get,
    apiVersion: ApiVersion.v2,
  ),
  parsaLendingInquiryCbs(
    title: 'Inquiry parsa lending cbs',
    path: 'loan/parsa-lending/inquiry/cbs',
    method: ApiMethod.post,
    apiVersion: ApiVersion.v2,
  );

  final String title;
  final String path;
  final ApiMethod method;
  final List<int> successStatusCodes;
  final ApiVersion apiVersion;
  final bool requireToken;
  final bool requireBase64EncodedBody;
  final bool requireEncryption;
  final bool requireDecryption;
  final bool requireEkycSign;
  final Duration connectTimeout;
  final Duration receiveTimeout;
  final Duration sendTimeout;

  const ApiProviderEnum({
    required this.title,
    required this.path,
    required this.method,
    this.successStatusCodes = const [200],
    this.apiVersion = ApiVersion.v1,
    this.requireToken = true,
    this.requireBase64EncodedBody = false,
    this.requireEncryption = true,
    this.requireDecryption = true,
    this.requireEkycSign = false,
    this.connectTimeout = const Duration(seconds: 60),
    this.receiveTimeout = const Duration(seconds: 60),
    this.sendTimeout = const Duration(seconds: 60),
  });
}
