import 'dart:io';

import 'package:args/args.dart';

import 'base_command.dart';

/// Command for setting up Supabase tables
class SetupCommand extends BaseCommand {
  @override
  String get name => 'setup';

  @override
  String get description => 'Create required Supabase tables automatically';

  @override
  ArgParser configureParser() {
    return ArgParser()..addFlag(
      'force',
      abbr: 'f',
      negatable: false,
      help: 'Drop existing tables and recreate them',
    );
  }

  @override
  Future<void> run(ArgResults results) async {
    final force = results['force'] as bool;

    if (service == null) {
      printError('Supabase service not initialized');
      exit(1);
    }

    try {
      printInfo('Setting up Supabase tables...');

      // SQL to create tables
      final sql = '''
-- Table for storing screens
create table if not exists stac_screens (
  id bigint generated by default as identity primary key,
  name text not null unique,
  json jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table for storing configurations
create table if not exists stac_config (
  id bigint generated by default as identity primary key,
  name text not null unique,
  json jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Table for version history
create table if not exists screen_versions (
  id bigint generated by default as identity primary key,
  screen text not null,
  version int not null,
  json jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table stac_screens enable row level security;
alter table stac_config enable row level security;
alter table screen_versions enable row level security;

-- Drop existing policies if they exist
drop policy if exists "Allow all operations on screens" on stac_screens;
drop policy if exists "Allow all operations on configs" on stac_config;
drop policy if exists "Allow all operations on versions" on screen_versions;

-- Create policies to allow all operations
create policy "Allow all operations on screens" on stac_screens for all using (true);
create policy "Allow all operations on configs" on stac_config for all using (true);
create policy "Allow all operations on versions" on screen_versions for all using (true);
''';

      // Execute SQL using Supabase RPC or direct SQL execution
      // Note: Supabase Dart client doesn't have direct SQL execution
      // We'll use the REST API to execute SQL
      await service!.executeSql(sql);

      printSuccess('Tables created successfully!');
      printInfo('Created tables: stac_screens, stac_config, screen_versions');
      printInfo('You can now upload screens using the upload command');
    } catch (e) {
      printError('Failed to setup tables: $e');
      printInfo('');
      printInfo('If you see permission errors, you may need to:');
      printInfo('1. Go to Supabase Dashboard > SQL Editor');
      printInfo('2. Run the SQL manually (shown above in the error)');
      printInfo('3. Or grant your service role key more permissions');
      exit(1);
    }
  }
}
