import 'package:flutter/widgets.dart';
import 'package:flutter_svg/flutter_svg.dart';

enum SvgIcons {
  nullIcon(''),
  faceId('face_id'),
  hamrahAval('ic_hamrah_aval'),
  gardeshgaryTextLogo('gardeshgary'),
  aboutUs('ic_about_us'),
  acceptor('ic_acceptor'),
  acceptorDark('ic_acceptor_dark'),
  accountHeader('ic_account_header'),
  accountHeaderDark('ic_account_header_dark'),
  add('ic_add'),
  addGiftCard('ic_add_gift_card'),
  addPlus('ic_add_plus'),
  addSquare('ic_add_square'),
  addSquareDark('ic_add_square_dark'),
  alertLight('ic_alert_light'),
  alertDark('ic_alert_dark'),
  icEditAccountImage('ic_edit_account_image'),
  icDelete('ic_delete'),
  amount('ic_amount'),
  aparat('ic_aparat'),
  arrowBack('ic_arrow_back'),
  arrowCircleDown('ic_arrow_circle_down'),
  arrowCircleUp('ic_arrow_circle_up'),
  arrowLeft('ic_arrow_left'),
  arrowLeftNew('ic_arrow_left_new'),
  icPackage('ic_package'),
  atm('ic_atm'),
  azkiLoan('ic_azki_loan'),
  azkiLoanDark('ic_azki_loan_dark'),
  azkiLoanHeader('ic_azki_loan_header'),
  azkiLoanHeaderDark('ic_azki_loan_header_dark'),
  azkiSarmaye('ic_azki_sarmaye'), // unused
  back('ic_back'),
  bankAccount('ic_bank_account'),
  bankLock('ic_bank_lock'),
  bankLockDark('ic_bank_lock_dark'),
  bankTransfer('ic_bank_transfer'),
  bankTransferDark('ic_bank_transfer_dark'),
  branch('ic_branch'),
  buttonNext('ic_button_next'),
  calendar('ic_calendar'),
  call('ic_call'),
  camera('ic_camera'),
  cameraDark('ic_camera_dark'),
  capture('ic_capture'),
  captureVisualTutorial('ic_capture_visual_tutorial'),
  captureVoiceTutorial('ic_capture_voice_tutorial'),
  card('ic_card'),
  cardBalance('ic_card_balance'),
  cardBalanceDark('ic_card_balance_dark'),
  cardCheck('ic_card_check'),
  cardDefault('ic_card_default'),
  cardDefaultDark('ic_card_default_dark'),
  cardDelete('ic_card_delete'),
  cardDeleteDark('ic_card_delete_dark'),
  cardDown('ic_card_down'),
  cardEdit('ic_card_edit'),
  cardEditDark('ic_card_edit_dark'),
  cardNumber('ic_card_number'),
  cardNumberDark('ic_card_number_dark'),
  cardSelected('ic_card_selected'),
  cardService('ic_card_service'),
  cardServiceDark('ic_card_service_dark'),
  cardServiceBlock('ic_card_service_block'),
  cardServiceBlockDark('ic_card_service_block_dark'),
  cardServicePasswordChange('ic_card_service_password_change'),
  cardServicePasswordChangeDark('ic_card_service_password_change_dark'),
  cardServiceReissue('ic_card_service_reissue'),
  cardServiceReissueDark('ic_card_service_reissue_dark'),
  cardToCard('ic_card_to_card'),
  loanListItemLight('loan_list_item_light'),
  loanListItemAlert('loan_list_item_alert'),
  loanDetailHistoryItemCalenderLight('loan_detail_history_item_calender_light'),
  loanDetailHistoryItemCalenderDark('loan_detail_history_item_calender_dark'),
  loanDetailHistoryItemPayed('loan_detail_history_item_payed'),
  loanDetailInformation('loan_detail_information'),
  loanDetailInformationLight('loan_detail_information_light'),
  loanDetailInformationDark('loan_detail_information_dark'),
  loanListNoItem('loan_list_no_item'),
  loanPayment('loan_payment'),
  loanPaymentDark('loan_payment_dark'),
  chargeWalletIcon('charge_wallet_icon'),
  loanPaymentSingleCardIcon('loan_payment_single_card_icon'),
  dialogAlert('dialog_alert'),
  cardToCardDark('ic_card_to_card_dark'),
  cardboard('ic_cardboard'),
  cardboardSelected('ic_cardboard_selected'),
  cameraHint('camera_hint'),
  videoHint('video_hint'),
  cbs('ic_cbs'),
  cbsDark('ic_cbs_dark'),
  cbsDetail('ic_cbs_detail'),
  cbsDetailDark('ic_cbs_detail_dark'),
  cbsSearch('ic_cbs_search'),
  changeCardPin('ic_change_card_pin'),
  changeCardPinDark('ic_change_card_pin_dark'),
  changePin('ic_change_pin'),
  changePinDark('ic_change_pin_dark'),
  charity('ic_charity'),
  charityDark('ic_charity_dark'),
  charityLogo('ic_charity_logo'),
  chart('ic_chart'),
  check('ic_check'),
  checkCircle('ic_check_circle'),
  checkInquiryStatus('ic_check_inquiry_status'),
  checkInquiryStatusDark('ic_check_inquiry_status_dark'),
  checkOwnerStatus('ic_check_owner_status'),
  checkOwnerStatusDark('ic_check_owner_status_dark'),
  checkReceive('ic_check_receive'),
  checkReceiveDark('ic_check_receive_dark'),
  checkStatus('ic_check_status'),
  checkStatusDark('ic_check_status_dark'),
  checkSubmit('ic_check_submit'),
  checkSubmitDark('ic_check_submit_dark'),
  checkTransfer('ic_check_transfer'),
  checkTransferDark('ic_check_transfer_dark'),
  childrenLoan('ic_children_loan'),
  childrenLoanDark('ic_children_loan_dark'),
  clock('ic_clock'),
  close('ic_close'),
  closeBold('ic_close_bold'),
  closeDeposit('ic_close_deposit'),
  closeDepositDark('ic_close_deposit_dark'),
  icPickContact('ic_pick_contact'),
  closeTutorial('ic_close_tutorial'), // not used
  contact('ic_contact'),
  contactList('ic_contact_list'),
  contactListDark('ic_contact_list_dark'),
  continueProcess('ic_continue_process'),
  continueProcessDark('ic_continue_process_dark'),
  copy('ic_copy'),
  creditCard('ic_credit_card'),
  creditCardDark('ic_credit_card_dark'),
  delete('ic_delete'),
  deleteDark('ic_delete_dark'),
  deleteAccount('ic_delete_account'),
  deleteAccountDark('ic_delete_account_dark'),
  deposit('ic_deposit'),
  depositBG('ic_deposit_bg'),
  depositBGDark('ic_deposit_bg_dark'),
  depositDetail('ic_deposit_detail'),
  depositDetailDark('ic_deposit_detail_dark'),
  depositNumber('ic_deposit_number'),
  depositNumberDark('ic_deposit_number_dark'),
  depositSelected('ic_deposit_selected'),
  // unused
  destinationCard('ic_destination_card'),
  destinationCardDark('ic_destination_card_dark'),
  destinationDeposit('ic_destination_deposit'),
  destinationDepositDark('ic_destination_deposit_dark'),
  destinationIban('ic_destination_iban'),
  destinationIbanDark('ic_destination_iban_dark'),
  //
  detail('ic_detail'),
  detailDark('ic_detail_dark'),
  directDynamicPin('ic_direct_dynamic_pin'),
  direction('ic_direction'),
  down('ic_down'),
  download('ic_download'),
  edit('ic_edit'),
  editAccountImage('ic_edit_account_image'),
  editDark('ic_edit_dark'),
  editProfile('ic_edit_profile'),
  electricBill('ic_electric_bill'),
  electricBillDark('ic_electric_bill_dark'),
  email('ic_email'),
  errorBoldCircle('ic_error_bold_circle'),
  failed('ic_failed'), // unused
  fav('ic_fav'), // commented
  filter('ic_filter'),
  finance('ic_finance'),
  financeSelected('ic_finance_selected'),
  financial('ic_financial'), // unused
  financialSelected('ic_financial_selected'), // unused
  fingerprint('ic_fingerprint'),
  fingerprintDark('ic_fingerprint_dark'),
  flash('ic_flash'),
  flashBold('ic_flash_bold'),
  flashSlashBold('ic_flash_slash_bold'),
  gallery('ic_gallery'),
  galleryDark('ic_gallery_dark'),
  gardeshgari('ic_gardeshgari'),
  gardeshgariSarmayeh('ic_gardeshgari_sarmayeh'),
  gasBill('ic_gas_bill'),
  gasBillDark('ic_gas_bill_dark'),
  gateway('ic_gateway'),
  gatewayDark('ic_gateway_dark'),
  getPin('ic_get_pin'),
  getPinDark('ic_get_pin_dark'),
  giftCard('ic_gift_card'),
  giftCardDark('ic_gift_card_dark'),
  giftCardCustom('ic_gift_card_custom'),
  giftCardCustomDark('ic_gift_card_custom_dark'),
  giftCardPrepared('ic_gift_card_prepared'),
  giftCardPreparedDark('ic_gift_card_prepared_dark'),
  hidePassword('ic_hide_password'),
  homeMain('ic_home_main'),
  homeMainSelected('ic_home_main_selected'),
  honarTicket('ic_honar_ticket'),
  honarTicketDark('ic_honar_ticket_dark'),
  inCome('in_come'),
  iban('ic_iban'),
  ibanDark('ic_iban_dark'),
  imageLoadError('image_load_error'),
  imageText('ic_image_text'),
  inIcon('ic_in'),
  inDarkIcon('ic_in_dark'),
  info('ic_info'),
  infoBold('ic_info_bold'),
  infoTutorial('ic_info_tutorial'), // unused
  instagram('ic_instagram'),
  internet('ic_internet'),
  internetDark('ic_internet_dark'),
  inviteCode('ic_invite_code'),
  inviteHeader('ic_invite_header'),
  inviteMember('ic_invite_member'),
  invoice('ic_invoice'),
  invoiceDark('ic_invoice_dark'),
  iran('ic_iran'),
  iranConcert('ic_iranconcert'),
  iranConcertDark('ic_iranconcert_dark'),
  irantic('ic_irantic'),
  iranticDark('ic_irantic_dark'),
  linkedin('ic_linkedin'),
  loan('ic_loan'),
  loanDark('ic_loan_dark'),
  location('ic_location'),
  lock('ic_lock'),
  lockRetrieval('ic_lock_retrieval'),
  lockRetrievalDark('ic_lock_retrieval_dark'),
  logout('ic_logout'),
  logoutDark('ic_logout_dark'),
  map('ic_map'),
  mapLocationGps('ic_map_location_gps'),
  mapSearch('ic_map_search'),
  marker('ic_marker'),
  megagasht('ic_megagasht'),
  megagashtDark('ic_megagasht_dark'),
  menu('ic_menu'),
  menuInternet('ic_menu_internet'),
  menuInternetDark('ic_menu_internet_dark'),
  menuMobile('ic_menu_mobile'),
  menuMobileDark('ic_menu_mobile_dark'),
  microLendingLoan('ic_micro_lending_loan'),
  microLendingLoanDark('ic_micro_lending_loan_dark'),
  militaryGuarantee('ic_military_guarantee'),
  militaryGuaranteeDark('ic_military_guarantee_dark'),
  minusSquare('ic_minus_square'),
  minusSquareDark('ic_minus_square_dark'),
  more('ic_more'),
  moreOptions('ic_more_options'),
  moreServices('ic_more_services'), // unused
  myOwn('ic_my_own'),
  notification('ic_notification'),
  notificationUnread('ic_notification_unread'),
  notificationUnreadDark('ic_notification_unread_dark'),
  other('ic_other'),
  otherSelected('ic_other_selected'),
  others('ic_others'), // unused
  out('ic_out'),
  outDark('ic_out_dark'),
  parsa('ic_parsa_lending'),
  parsaDark('ic_parsa_lending_dark'),
  paya('ic_paya'),
  payaDark('ic_paya_dark'),
  pdfFile('ic_pdf_file'),
  person('ic_person'),
  phone('ic_phone'),
  pichak('ic_pichak'),
  pichakDark('ic_pichak_dark'),
  pointPay('ic_point_pay'), // unused
  pointReceive('ic_point_receive'), // unused
  profile('ic_profile'),
  profileMain('ic_profile_main'),
  profileMainSelected('ic_profile_main_selected'),
  promissory('ic_promissory'),
  promissoryCancel('ic_promissory_cancel'),
  promissoryContinue('ic_promissory_continue'),
  promissoryDark('ic_promissory_dark'),
  promissoryDetail('ic_promissory_detail'),
  promissoryDetailDark('ic_promissory_detail_dark'),
  promissoryEndorsement('ic_promissory_endorsement'),
  promissoryEndorsementDark('ic_promissory_endorsement_dark'),
  promissoryFinalizeHistory('ic_promissory_finalize_history'),
  promissoryFinalizedServices('ic_promissory_finalized_services'),
  promissoryGuarantee('ic_promissory_guarantee'),
  promissoryGuaranteeDark('ic_promissory_guarantee_dark'),
  promissoryInquiry('ic_promissory_inquiry'),
  promissoryInquiryDark('ic_promissory_inquiry_dark'),
  promissoryRequest('ic_promissory_request'),
  promissoryRequestDark('ic_promissory_request_dark'),
  promissoryRequestHistory('ic_promissory_request_history'),
  promissorySettlement('ic_promissory_settlement'),
  promissorySettlementDark('ic_promissory_settlement_dark'),
  promissorySettlementGradual('ic_promissory_settlement_gradual'),
  promissorySettlementGradualDark('ic_promissory_settlement_gradual_dark'),
  promissoryShow('ic_promissory_show'),
  rayanCard('ic_rayan_card'),
  rayanCardDark('ic_rayan_card_dark'),
  receiveAmount('ic_receive_amount'),
  receiveAmountDark('receive_amount_dark'),
  recording('ic_recording'),
  refresh('ic_refresh'),
  requestAcceptor('ic_request_acceptor'),
  requestAcceptorDark('ic_request_acceptor_dark'),
  requestCard('ic_request_card'),
  requestCardDark('ic_request_card_dark'),
  retailLoan('ic_retail_loan'),
  retailLoanDark('ic_retail_loan_dark'),
  icChargeEmptyListLight('ic_charge_empty_list_light'),
  icChargeEmptyListDark('ic_charge_empty_list_dark'),
  icPackageEmptyList('ic_package_empty_list'),
  icPackageEmptyListLight('ic_package_empty_list_light'),
  icPackageEmptyListDark('ic_package_empty_list_dark'),
  icIrancell('ic_irancell'),
  icHamrahAval('ic_hamrah_aval'),
  icRightel('ic_rightel'),
  rules('ic_rules'),
  safeBox('ic_safe_box'),
  safeBoxDark('ic_safe_box_dark'),
  satna('ic_satna'),
  satnaDark('ic_satna_dark'),
  scanner('ic_scanner'),
  scannerDark('ic_scanner_dark'),
  scroll('ic_scroll'),
  search('ic_search'),
  settings('ic_settings'),
  share('ic_share'),
  shareCard('ic_share_card'),
  shareCardDark('ic_share_card_dark'),
  shareDark('ic_share_dark'),
  shareDeposit('ic_share_deposit'),
  shareDepositDark('ic_share_deposit_dark'),
  shareIban('ic_share_iban'), // commented
  shareIbanDark('ic_share_iban_dark'), // commented
  shareImage('ic_share_image'),
  shareText('ic_share_text'),
  shetab('shetab'),
  show('ic_show'), // unused
  showPassword('ic_show_password'),
  simCharge('ic_sim_charge'),
  simChargeDark('ic_sim_charge_dark'),
  smsDynamicPin('ic_sms_dynamic_pin'),
  star('ic_star'), // unused
  starFill('ic_star_fill'), // unused
  status('ic_status'),
  storedDeposit('ic_stored_deposit'),
  success('ic_success'),
  successNew('ic_success_new'),
  support('ic_support'),
  switchCard('ic_switch_card'),
  telBill('ic_tel_bill'),
  telBillDark('ic_tel_bill_dark'),
  textDark('ic_text_dark'),
  theme('ic_theme'),
  themeDark('ic_theme_dark'),
  tickCircle('ic_tick_circle'),
  tickCircleGreen('ic_tick_circle_green'),
  timer('ic_timer'),
  tobank('ic_tobank'),
  tobankLogo('ic_tobank_logo'),
  tobankQrcode('ic_tobank_qrcode'), // unused
  tobankRed('ic_tobank_red'), // width 90 -> size 18
  tobankWhite('ic_tobank_white'),
  touch('ic_touch'),
  touchDark('ic_touch_dark'),
  transaction('ic_transaction'),
  transactionDark('ic_transaction_dark'),
  transactionFailed('ic_transaction_failed'),
  transactionItemFailed('ic_transaction_item_failed'),
  transactionItemFailedDark('ic_transaction_item_failed_dark'),
  transactionItemPending('ic_transaction_item_pending'),
  transactionItemPendingDark('ic_transaction_item_pending_dark'),
  transactionItemSuccess('ic_transaction_item_success'),
  transactionItemSuccessDark('ic_transaction_item_success_dark'),
  transactionMain('ic_transaction_main'),
  transactionMainSelected('ic_transaction_main_selected'),
  transactionPending('ic_transaction_pending'),
  transactionSuccess('ic_transaction_success'),
  transferAmount('ic_transfer_amount'),
  transferAmountDark('ic_transfer_amount_dark'),
  tutorial('ic_tutorial'), // unused
  upload('ic_upload'), // unused
  userProfile('ic_user_profile'),
  userProfileDark('ic_user_profile_dark'),
  visualTutorial('ic_visual_tutorial'),
  visualTutorialDark('ic_visual_tutorial_dark'),
  voice('ic_voice'), // unused
  voiceTutorial('ic_voice_tutorial'),
  voiceTutorialDark('ic_voice_tutorial_dark'),
  wallet('ic_wallet'),
  walletBalance('ic_wallet_balance'), // unused
  walletDark('ic_wallet_dark'),
  warning('ic_warning'),
  warningBoldTriangle('ic_warning_bold_triangle'),
  warningOrangeCircle('ic_warning_orange_circle'), // only one use
  warningRed('ic_warning_red'),
  waterBill('ic_water_bill'),
  waterBillDark('ic_water_bill_dark'),
  website('ic_website'),
  wheelchair('ic_wheelchair'), // unused
  // >>>
  mapMarker('map_marker'),
  outCome('out_come'),
  signPdf('sign-pdf');

  final String slug;

  const SvgIcons(this.slug);

  String get assetPath => 'assets/icons/$slug.svg';
}

class SvgIcon extends StatelessWidget {
  const SvgIcon(
    this.data, {
    super.key,
    this.color,
    this.colorFilter,
    this.size,
  });

  final Color? color;
  final ColorFilter? colorFilter;
  final double? size;
  final SvgIcons data;

  @override
  Widget build(BuildContext context) {
    final theme = IconTheme.of(context);

    return SvgPicture.asset(
      data.assetPath,
      colorFilter: colorFilter ?? (color == null ? null : ColorFilter.mode(color ?? theme.color!, BlendMode.srcIn)),
      height: size,
      width: size,
    );
  }
}
